# Generated by Django 4.1.5 on 2023-01-22 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("Report", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exchange",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("exchange_name", models.CharField(max_length=255)),
                ("api_key", models.CharField(max_length=255)),
                ("secret_key", models.CharField(max_length=255)),
            ],
        ),
    ]
